remote_theme: mmistakes/minimal-mistakes@4.26.2
title: National Parking Platform
google-analytics-id: G-B44QGPWWHK
plugins:
- jekyll-remote-theme
- jekyll-include-cache
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
